import collections

generators = collections.OrderedDict([
    ("czech-adjective", {
        'label': 'generátor tvarů českých přídavných jmen',
        'input-fields': [
            'Kořen 1. stupně přídavného jména ("mlad" pro mladý, "jarn" pro jarní, "rozmarn" pro rozmarný atd.)',
            '1. pád 2. stupně přídavného jména ("mladší", "jarnější", "rozmarnější" atd.)'
        ],
        'patterns': {'mladý': [
            '/1ý',
            '/1ého',
            '/1ému',
            '/1ého',
            '/1ý',
            '/1ém',
            '/1ým',
            '/1ý',
            '/1ého',
            '/1ému',
            '/1ý',
            '/1ý',
            '/1ém',
            '/1ým',
            '/1á',
            '/1é',
            '/1é',
            '/1ou',
            '/1á',
            '/1é',
            '/1ou', # instrumental, feminine, singular, positive
            '/1é',
            '/1ého',
            '/1ému',
            '/1é',
            '/1é',
            '/1ém',
            '/1ým',
            '',  # may require softening of letter before
            '/1ých',
            '/1ým',
            '/1é',
            '',
            '/1ých',
            '/1ými',
            '/1é',
            '/1ých',
            '/1ým',
            '/1é',
            '/1é',
            '/1ých',
            '/1ými',  # instrumental, inanimate masculine, plural, positive
            '/1é',
            '/1ých',
            '/1ým',
            '/1é',
            '/1é',
            '/1ých',
            '/1ými',
            '/1á',
            '/1ých',
            '/1ým',
            '/1á',
            '/1á',
            '/1ých',
            '/1ými',
            '/2',  # nominative, animate masculine, singular, comparative
            '/2ho',
            '/2mu',
            '/2ho',
            '/2',
            '/2m',
            '/2m',
            '/2',
            '/2ho',
            '/2mu',
            '/2',
            '/2',
            '/2m',
            '/2m',
            '/2',
            '/2',
            '/2',
            '/2',
            '/2',
            '/2',
            '/2',  # instrumental, feminine, singular, comparative
            '/2',
            '/2ho',
            '/2mu',
            '/2',
            '/2',
            '/2m',
            '/2m',
            '/2',
            '/2ch',
            '/2m',
            '/2',
            '/2',
            '/2ch',
            '/2mi',  # instrumental, animate masculine, plural, comparative
            '/2',
            '/2ch',
            '/2m',
            '/2',
            '/2',
            '/2ch',
            '/2mi',
            '/2',
            '/2ch',
            '/2m',
            '/2',
            '/2',
            '/2ch',
            '/2mi',
            '/2',
            '/2ch',
            '/2m',
            '/2',
            '/2',
            '/2ch',
            '/2mi',
            'nej/2',  # nominative, animate masculine, singular, superlative
            'nej/2ho',
            'nej/2mu',
            'nej/2ho',
            'nej/2',
            'nej/2m',
            'nej/2m',
            'nej/2',
            'nej/2ho',
            'nej/2mu',
            'nej/2',
            'nej/2',
            'nej/2m',
            'nej/2m',
            'nej/2',
            'nej/2',
            'nej/2',
            'nej/2',
            'nej/2',
            'nej/2',
            'nej/2',  # instrumental, feminine, singular, superlative
            'nej/2',
            'nej/2ho',
            'nej/2mu',
            'nej/2',
            'nej/2',
            'nej/2m',
            'nej/2m',
            'nej/2',
            'nej/2ch',
            'nej/2m',
            'nej/2',
            'nej/2',
            'nej/2ch',
            'nej/2mi',  # instrumental, animate masculine, plural, superlative
            'nej/2',
            'nej/2ch',
            'nej/2m',
            'nej/2',
            'nej/2',
            'nej/2ch',
            'nej/2mi',
            'nej/2',
            'nej/2ch',
            'nej/2m',
            'nej/2',
            'nej/2',
            'nej/2ch',
            'nej/2mi',
            'nej/2',
            'nej/2ch',
            'nej/2m',
            'nej/2',
            'nej/2',
            'nej/2ch',
            'nej/2mi'
        ], 'jarní': [
            # TODO
        ]}
    })
])